 let userScore = 0;
 let compScore = 0;

 let choices = document.querySelectorAll(".choice");
 let showWinner = document.querySelector(".msg");

const genCompChoice = () => { //Function for Generating computer Choice
  let option = ["rock" , "paper" , "scissors"];
  const randIdx = Math.floor( Math.random()*3 ); // Math.random() Function generates random number between 0 to 1 if  we multiply this with n then it will give the random number between 0 to n-1. floor function used to remove the floating value.
  return option[randIdx]; //returns random option generated by computer
}

 const  playGame = (userChoice) => {
  console.log("user choice = " ,userChoice);

  const compChoice = genCompChoice();
  
  console.log("comp choice = ", compChoice);

  if(compChoice == "rock")
  {
    if(userChoice == "scissors") {
     
      console.log("comp wins");
      showCompScore(compChoice , userChoice);
    }
    else if(userChoice == "paper") {
      
      console.log("user wins");
      showUserScore(compChoice , userChoice);

    }
    else {
      console.log("Game Draw");
      drawConditon();
    }
  }
  else if(compChoice == "paper") {

    if(userChoice == "rock") {
     
      console.log("comp wins");
      showCompScore(compChoice , userChoice);
    }
    else if(userChoice == "scissors") {
     
      console.log("user wins");
      showUserScore(compChoice , userChoice);
    }
    else {
      
      console.log("Game Draw");
      drawConditon();
    }

  }
  else if(compChoice == "scissors") {
   
    if(userChoice == "rock") {
     
      console.log("user wins");
      showUserScore(compChoice , userChoice);
    }
    else if(userChoice == "paper") {
     
      console.log("comp wins");
      showCompScore(compChoice , userChoice);
    }
    else {
     
      console.log("Game Draw");
      drawConditon();
    }
  }
 }

 const drawConditon = () => {

  showWinner.innerText = "Game Was Draw.";
  showWinner.style.backgroundColor = " rgb(1, 1, 27)";
 }

 const showUserScore = (compChoice, userChoice) => {
 
  userScore++;
   let userScoreClass = document.querySelector(".userScore");
   userScoreClass.innerText = userScore;
   showWinner.innerText = `User wins the Game. ${userChoice}  beats ${compChoice}`;
   showWinner.style.backgroundColor = "green";
   
 }

 const showCompScore = (compChoice, userChoice) => {
  
  compScore++;
   let compScoreClass = document.querySelector(".compScore");
   compScoreClass.innerText = compScore;
   showWinner.innerText = `Computer wins the Game. ${compChoice} beats ${userChoice}`;
   showWinner.style.backgroundColor = "red";
   
 }

 
 choices.forEach((choice) => {
 
   choice.addEventListener("click", () => {
    const userChoice = choice.getAttribute("id");
    playGame(userChoice);
     })
 });










 